

services:

  django:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      - REMOTE_DEBUGGING_PORT=5678
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=PharmacyOnDuty.settings

  db:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  worker:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    command: uv run celery -A PharmacyOnDuty worker -l info --hostname=scraper@%%h
    environment:
      - DJANGO_SETTINGS_MODULE=PharmacyOnDuty.settings
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  beat:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    command: uv run celery -A PharmacyOnDuty beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=PharmacyOnDuty.settings
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgis-data:
  redis_data: